"""
src/main.py — Growth-strategy pipeline (target: 100K followers / 6 months).

KEY CHANGES vs. the old multi-style/multi-topic version:
  1. ONE visual format only (_single_carousel_frame via VideoCreator).
     No more random kinetic/documentary/cartoon/carousel selection.
     Format consistency is a ranking signal for a new account — looking
     like a different product every day resets the algorithm's read on
     your niche. We post Reels (not carousels) because Reels still win
     on raw discovery/Explore potential for a 0-follower account; once
     we're past the cold-start phase, carousels can come back as a
     secondary format for save-heavy content.
  2. fact_data["engage_line"] (comment/save/share trigger, generated by
     fact_gen.py) is rendered on-screen AND folded into the caption —
     this is the actual fix for the 0-like/0-comment/0-save reels.
  3. 1 post/day (see config.POSTS_PER_DAY / DAY_ROTATION), not 3 — quality
     and consistency over volume, per the research and your own call.
"""

import os, sys, json, logging
from datetime import datetime, timezone
from pathlib import Path

ROOT       = Path(__file__).parent.parent
OUTPUT_DIR = ROOT / "output"
VIDEOS_DIR = OUTPUT_DIR / "videos"
LOGS_DIR   = OUTPUT_DIR / "logs"
IMAGES_DIR = OUTPUT_DIR / "images"
AUDIO_DIR  = OUTPUT_DIR / "audio"

for d in [VIDEOS_DIR, LOGS_DIR, IMAGES_DIR, OUTPUT_DIR/"music", AUDIO_DIR]:
    d.mkdir(parents=True, exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler(LOGS_DIR/f"run_{datetime.now().strftime('%Y%m%d_%H%M%S')}.log"),
    ],
)
log = logging.getLogger(__name__)

sys.path.insert(0, str(ROOT/"src"))
from config      import (TOPICS, LANGUAGES, get_hashtags,
                          get_duration_and_voice, get_music_volume)
from fact_gen    import FactGenerator
from video       import VideoCreator
from music       import MusicManager
from narration   import generate_narration
from audio_mixer import mix_audio
from poster      import InstagramPoster
from config      import get_series_label
from fact_memory import FactMemory

REEL_STYLE = "carousel_visual"   # the one style video.py actually renders


def run_pipeline(topic_key: str, lang: str = "hi",
                 dry_run: bool = False) -> dict:
    topic  = TOPICS[topic_key]
    result = {
        "timestamp":  datetime.now(timezone.utc).isoformat(),
        "topic":      topic_key,
        "lang":       lang,
        "status":     "started",
        "dry_run":    dry_run,
        "reel_style": REEL_STYLE,
    }

    try:
        # 1 — Duration (no voiceover — automation-only constraint)
        duration, use_voice = get_duration_and_voice()
        result["duration"]  = duration
        result["use_voice"] = use_voice
        log.info(f"▶ [{topic['name_hi']}] {duration}s")

        # 2 — Generate fact + engagement trigger (the core growth fix)
        generator = FactGenerator()
        fact_data = generator.generate(topic_key, topic, lang)

        # 2b — Series identity: auto-incrementing episode number per topic.
        # This is what turns a viewer into a follower ("I want the next one").
        episode      = FactMemory().next_episode(topic_key)
        series_label = get_series_label(topic_key, episode, lang)
        fact_data["series_label"] = series_label
        result["series_label"]    = series_label
        log.info(f"📺 Series: {series_label}")

        result["hook"]        = fact_data["hook"]
        result["category"]    = fact_data.get("fact_category", "")
        result["engage_line"] = fact_data.get("engage_line", "")
        log.info(f"✅ Fact: {fact_data['hook'][:60]}")
        log.info(f"💬 Engage line: {fact_data.get('engage_line','')[:60]}")

        # 3 — Image
        image_path, img_source, _ = generator.fetch_image(
            topic["image_keywords"], topic_key
        )
        result["image_source"] = img_source
        log.info(f"✅ Image [{img_source}]")

        # 4 — Music
        music_mgr  = MusicManager()
        music_path = music_mgr.get_track(topic["music_mood"], topic_key)
        vol        = get_music_volume(topic["music_energy"])

        # 5 — Voiceover (disabled by business decision — kept for future use)
        final_audio   = music_path
        narr_duration = 0.0
        if use_voice:
            log.info("🎙 Generating voiceover...")
            narr, narr_duration = generate_narration(
                hook=fact_data["hook"], body=fact_data["body"],
                lang=lang, topic_key=topic_key, output_dir=AUDIO_DIR,
                reel_duration=duration,
            )
            if narr and narr.exists():
                if narr_duration > duration - 2:
                    duration = min(45, int(narr_duration) + 4)
                    result["duration"] = duration
                    log.info(f"📐 Extended to {duration}s")
                final_audio = mix_audio(
                    music_path=music_path, narration_path=narr,
                    output_dir=AUDIO_DIR, duration=duration,
                )
                log.info(f"✅ Narration: {narr_duration:.1f}s")
            else:
                log.warning("Voiceover failed — music only")
                narr_duration = 0.0

        # 6 — Render reel (single consistent visual style)
        creator    = VideoCreator()
        video_path = creator.create_reel(
            image_path    = image_path or Path("/dev/null"),
            music_path    = final_audio,
            fact_data     = fact_data,
            topic         = topic,
            lang          = lang,
            output_dir    = VIDEOS_DIR,
            reel_style    = REEL_STYLE,
            duration      = duration,
            music_volume  = vol,
            scene_paths   = None,
            narr_duration = narr_duration,
        )
        result["video_path"] = str(video_path)

        # 7 — Post — caption leads with the series tag (recognition + SEO),
        # then the hook/answer, then the engage_line (comment/save/share
        # trigger), then hashtags.
        if dry_run:
            log.info("🔵 Dry run — skipping post")
            result["status"] = "dry_run_ok"
        else:
            poster      = InstagramPoster()
            hashtags    = get_hashtags(topic_key, lang)
            caption_raw = fact_data.get("caption", fact_data["hook"])
            engage_line = fact_data.get("engage_line", "")
            if engage_line and engage_line not in caption_raw:
                caption_raw = f"{caption_raw}\n\n{engage_line}"
            caption  = f"📺 {series_label}\n\n{caption_raw}\n\n{hashtags}"
            media_id = poster.post_reel(
                video_path, caption,
                topic_key=topic_key,
                first_comment=engage_line,
            )
            result["media_id"] = str(media_id)
            result["status"]   = "posted"
            log.info(f"✅ Posted! ID: {media_id}")

    except Exception as exc:
        result["status"] = "failed"
        result["error"]  = str(exc)
        log.error(f"❌ {exc}", exc_info=True)
        sys.exit(1)
    finally:
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        (LOGS_DIR / f"run_{topic_key}_{lang}_{ts}.json").write_text(
            json.dumps(result, indent=2, ensure_ascii=False))
    return result


if __name__ == "__main__":
    args    = sys.argv[1:]
    dry_run = "--dry-run" in args
    args    = [a for a in args if a != "--dry-run"]

    if not args or args[0] != "run":
        print("Usage: python src/main.py run <topic> [--dry-run]")
        print(f"Topics: {', '.join(TOPICS)}")
        sys.exit(0)

    topic_key = args[1] if len(args) > 1 else "gk"
    if topic_key not in TOPICS:
        print(f"Unknown topic: {topic_key}. Valid: {', '.join(TOPICS)}")
        sys.exit(1)
    run_pipeline(topic_key, "hi", dry_run=dry_run)
